@startuml context
actor "Usuarios Finales" as User
actor "Empresas Clientes" as Client
actor "Administradores de ABCall" as Admin
actor "Google Cloud Services" as GCloud
actor "Sistemas de Clientes" as ClientSystems

rectangle "ABCall" {
    component "Frontend Web (Angular)" as WebApp
    component "Mobile App (Ionic)" as MobileApp
    component "Backend (Microservicios)" as Backend
}

User --> WebApp : Interactúa con
User --> MobileApp : Interactúa con
Client --> WebApp : Configuración de flujos y consultas
Admin --> WebApp : Administración y Monitoreo
WebApp --> Backend : Interacciones con Backend
MobileApp --> Backend : Interacciones con Backend

Backend --> GCloud : Utiliza servicios de Google Cloud
Backend --> ClientSystems : Integración y sincronización de datos
@enduml
