@startuml deployment-diagram
skinparam packageStyle rectangle

node "GCP Project" {
    node "API Gateway" {
    }

    node "Google Kubernetes Engine" {

        rectangle mediators {
        }

        rectangle auth {
        }

        rectangle "business logic" {
        }

        rectangle automation {
        }

        [mediators] -down-> [business logic] : gRPC
        [business logic] -right-> [commons] : gRPC

        rectangle commons {
        }

        
        
    }

    node "Cloud SQL (PostgreSQL)" {
    }

    node "Redis Cache" {
    }
    
    node "Public Internet Node" {
    }

    node "GCP Pub/Sub" {
    }

    node "Firebase" {
    }
}

node "Mobile Devices" {
}

node "Notification Engine" {
}

node "AI Supplier" {
}

[Public Internet Node] -down-> [API Gateway] : https
[Mobile Devices] -down-> [API Gateway] : https

[API Gateway] -down-> [Google Kubernetes Engine] : gRPC
[Google Kubernetes Engine] -down-> [Cloud SQL (PostgreSQL)] : jdbc
[Google Kubernetes Engine] -down-> [Redis Cache] : tcp
[Google Kubernetes Engine] <-up-> [GCP Pub/Sub] : tcp
[Google Kubernetes Engine] -down-> [Firebase] : https
[Google Kubernetes Engine] -down-> [Notification Engine] : https

[Google Kubernetes Engine] -down-> [AI Supplier] : https



@enduml
