services:
  pubsub:
      image: google/cloud-sdk:latest
      platform: linux/amd64
      container_name: pubsub_emulator
      command: gcloud beta emulators pubsub start --project=my-project --host-port=0.0.0.0:8085
      ports:
        - "8085:8085"
      environment:
        PUBSUB_EMULATOR_HOST: localhost:8085
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: abcall
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
    